# Site
title: Alexander O. Smith
description: PhD Student, iSchool, Syracuse University
url: https://aos11409.github.io
logo: aos.png                                         # Site logo
disqus_shortname: https-aos11409-github-io
locale: en_US

# Left Block Images
background:
  homepage: images/profile.jpg                 # this image will be shown on homepage's left block
  post-list: images/profile.jpg                # this image will be shown on post list page
  default-post: images/profile.jpg             # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-113001384-1

# Social Links
#email:             email
#google.plus:        username
#twitter:            username
facebook:           aos11409
github:             aos11409
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           aos11409
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - _site
  - src
  - vendor
  - LICENSE
  - THEME_LICENSE
  - Rakefile
  - .sass-cache
  - .DS_Store
