# Site
title: 'Spirit Twins Lacrosse™️'
description: 'The Arnold Twins are of the Oneida Nation of Wisconsin and have been playing box lacrosse with the Onondaga Redhawks since they were 3 years old and have over 21 years experience in lacrosse.'
url: https://spirittwinslacrosse.com
logo: spirit-twins-lacrosse-logo.png                                         # Site logo
#disqus_shortname: username
locale: en_US

# Left Block Images
background:
  homepage: images/onondaga-lake.jpg                           # this image will be shown on homepage's left block
  post-list: images/onondaga-lake.jpg             # this image will be shown on post list page
  default-post: images/wooden-lacrosse-stick-love-laxcon-min.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache


# Collections
collections:
  bios:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _bios
  - scope:
      path: ""
      type: bios
    values:
      layout: page
      related: true

# Social Links
email:             spirittwinslacrosse@gmail.com
twitter:            spirittwinslax
facebook:           spirittwinslax
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:           username
#xing:              username
instagram:          spirittwinslax
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
podcast:           'https://www.buzzsprout.com/1073554'
#apple:             'https://podcasts.apple.com/us/podcast/the-two-man-game-presented-by-spirit-twins-lacrosse/id1513782800'
#google:            'https://podcasts.google.com/?feed=aHR0cHM6Ly9mZWVkcy5idXp6c3Byb3V0LmNvbS8xMDczNTU0LnJzcw=='
#spotify:           'https://open.spotify.com/show/33DGNJgMqyTB3gTLolf1Jn'


# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag


# Exclude list
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - _site
  - src
  - vendor
  - LICENSE
  - THEME_LICENSE
  - Rakefile
  - .sass-cache
  - .DS_Store
